#!/bin/sh

set -uexo pipefail

echo "Checking for .github/workflows/build.yml.jinja changes..."

files=( $(git diff-index --cached HEAD --name-only) )

echo ">>>>" >> /tmp/pre-commit

for file in ${files[@]}
do
	echo $file >> /tmp/pre-commit
	if [[ "$file" == ".github/workflows/build.yml.jinja" ]]
	then
		echo "Change detected, re-rendering"
		./builder.py render
		git add .github/workflows || true
	fi
done
echo "<<<<" >> /tmp/pre-commit
