FROM {host_arch}/{host_distro}

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update; \
  apt-get install -y \
    {packages}; \
  apt-get clean

WORKDIR /root

COPY ./rendered/distcc-cross-compiler-host-debian/{host_arch}/etc/default/* /etc/default/
COPY ./rendered/distcc-cross-compiler-host-debian/{host_arch}/etc/init.d/* /etc/init.d/
COPY ./rendered/distcc-cross-compiler-host-debian/{host_arch}/etc/logrotate.d/* /etc/logrotate.d/

COPY ./scripts/distcc-cross-compiler-host-debian/setup.sh setup.sh
COPY ./scripts/distcc-cross-compiler-host-debian/run.sh run.sh

RUN \
  chmod +x /etc/init.d/distccd-* && \
  chmod +x setup.sh && \
  chmod +x run.sh && \
  ./setup.sh

CMD ./run.sh
