# Rendered from .github/workflows/build.yml.jinja

name: Build archlinux images

on:
  push:
    branches: ['*']
    tags: ['*']

jobs:
  build-amd64-host:
    name: |
      Build archlinux host amd64
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        submodules: recursive

    - name: Install emulation dependencies
      run: |
        sudo apt-get update -q -y
        sudo apt-get -qq install -y qemu qemu-user-static
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

    - name: Install pip requirements
      run: |
        pip3 install -r requirements.txt

    - name: Build host image
      run: |
        ./builder.py build-host \
          --distro archlinux \
          --host-arch amd64 \
          --tag $(basename ${{ github.event.ref }})

  build-amd64-clients:
    name: |
      Build archlinux client ${{ matrix.compiler_arch }} (host: amd64)
    runs-on: ubuntu-latest
    needs: build-amd64-host

    strategy:
      matrix:
        include:
        - host_arch: amd64
          compiler_arch: amd64

        - host_arch: amd64
          compiler_arch: arm32v5

        - host_arch: amd64
          compiler_arch: arm32v6

        - host_arch: amd64
          compiler_arch: arm32v7

        - host_arch: amd64
          compiler_arch: arm64v8


    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        submodules: recursive

    - name: Install emulation dependencies
      run: |
        sudo apt-get update -q -y
        sudo apt-get -qq install -y qemu qemu-user-static
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

    - name: Install pip requirements
      run: |
        pip3 install -r requirements.txt

    - name: Build client image
      run: |
        ./builder.py build-client \
          --distro archlinux \
          --client-arch ${{ matrix.compiler_arch }} \
          --tag $(basename ${{ github.event.ref }})

    - name: Run tests
      run: |
        ./builder.py test \
          --distro archlinux \
          --host-arch amd64 \
          --client-arch ${{ matrix.compiler_arch }} \
          --tag $(basename ${{ github.event.ref }})



